# Generated by Django 3.2.14 on 2022-07-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='hide_emails',
            new_name='hide_email',
        ),
    ]
